Add friends likes
PiFFFko/java-filmorate pull request #4
Opened 2023-03-17 15:02 UTC by PiFFFko

2023-03-17 20:30 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +import org.springframework.http.HttpStatus;
Этот импорт не используется

2023-03-17 20:32 UTC, EvgenyKoptubenko commented
Можно добавлять одного и того же пользователя несколько раз с одинаковыми параметрами.
Если добавление уникальности в следующих спринтах, тогда исправлять не нужно

2023-03-17 20:33 UTC, EvgenyKoptubenko commented
При отправке такого запроса
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name2":"nameItem",
	"email":"email3email.com",
  "login":"login"
}'

Падает 500
{
	"timestamp": "2023-03-17T20:32:30.514+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"message": "Validation failed for object='user'. Error count: 1",
	"path": "/users"
}

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Circular view path [users]: would dispatch back to the current handler URL [/users] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)] with root cause

javax.servlet.ServletException: Circular view path [users]: would dispatch back to the current handler URL [/users] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
	at org.springframework.web.servlet.view.InternalResourceView.prepareForRendering(InternalResourceView.java:210) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:148) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1405) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1149) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.25.jar:5.3.25]

2023-03-17 20:37 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть замечание по добавлению/обновлению пользователя

2023-03-21 11:28 UTC, PiFFFko commented
> апр
арп


> Можно добавлять одного и того же пользователя несколько раз с одинаковыми параметрами. Если добавление уникальности в следующих спринтах, тогда исправлять не нужно

Доброго дня. Не могу сказать, будет ли такое условие в следующих спринтах, но как появится необходимость, то сразу добавлю.

2023-04-06 12:40 UTC, merged