feat: функционал в рамках тз11
PiFFFko/java-filmorate pull request #5
Opened 2023-04-19 15:49 UTC by PiFFFko

2023-04-20 01:41 UTC, EvgenyKoptubenko commented
UserValidationTest - можно везде убрать модификаторы public

2023-04-20 01:42 UTC, EvgenyKoptubenko commented
UserValidationTest
@Test
    public void blankLoginShouldFailValidation(){
        user.setEmail(CORRECT_MAIL);
        user.setLogin("");
        Set<ConstraintViolation<User>> violations =validator.validate(user);
        Assertions.assertFalse(violations.isEmpty());
    }

    @Test
    public void loginWithSpacesShouldFailValidation(){
        user.setEmail(CORRECT_MAIL);
        user.setLogin("lo gin");
        Set<ConstraintViolation<User>> violations =validator.validate(user);
        Assertions.assertFalse(violations.isEmpty());
    }

Функции отличаются только одним параметром. Если есть желание, попробуй сделать параметризованные функции - это сократит количество кода https://www.baeldung.com/parameterized-tests-junit-5

2023-04-20 01:43 UTC, EvgenyKoptubenko commented
FilmValidationTest - есть неиспользуемые импорты

2023-04-20 01:46 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ErrorResponse(e.getMessage());
методы, которые обрабатывают NOT_FOUND можно объединить в один https://www.baeldung.com/exception-handling-for-rest-with-spring

2023-04-20 01:47 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    private Genre updateGenre(@RequestBody Genre genre) {
Почему эти два метода private?

2023-04-20 01:53 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private FriendStorage friendStorage;
Эта переменная нигде не используется

2023-04-20 02:02 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
На 39-й строке в логе нет плейсхолдера, т.е. фильм не выведется в лог. И почему-то для логирования успешного события используется error

2023-04-20 02:02 UTC, EvgenyKoptubenko commented on pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
spring-boot-starter-test зависимость добавлена 2 раза

2023-04-20 02:04 UTC, EvgenyKoptubenko commented
в файле README.md должна быть ссылка на файл диаграммы.

2023-04-20 02:05 UTC, EvgenyKoptubenko commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
Для чего к каждой таблице приделано слово PUBLIC.?

2023-04-20 02:18 UTC, EvgenyKoptubenko commented
Должен быть MpaDbStorage

2023-04-20 02:19 UTC, EvgenyKoptubenko commented
Должно быть добавлено интеграционное тестирование, но в PR нет измененных или добавленных тестов

2023-04-20 02:19 UTC, EvgenyKoptubenko requested changes
Есть несколько замечаний. Поправь, пожалуйста.

2023-04-20 11:56 UTC, PiFFFko commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
Генерировал таблицы в DBeavere и PUBLIC это название схемы в рамках которой, создаются таблицы. Оставил для надежности. Но сейчас попробовал и без указания схемы вроде без проблем генерируется.
![image](https://user-images.githubusercontent.com/38191066/233358360-7e6f1f5f-9a6b-4c06-9b64-28ee09c16a15.png)

2023-04-20 12:00 UTC, PiFFFko commented
> Должен быть MpaDbStorage

У меня RatingDbStorage. Критично? Переименовать?

2023-04-21 03:12 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-04-27 13:09 UTC, merged